// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Alten_Gonzalez.Models
{
    public partial class Carrelli
    {
        public Carrelli()
        {
            ProdottiCarrellos = new HashSet<ProdottiCarrello>();
        }

        public int Id { get; set; }
        public int IdUtente { get; set; }

        public virtual Utenti IdUtenteNavigation { get; set; }
        public virtual ICollection<ProdottiCarrello> ProdottiCarrellos { get; set; }
    }
}