// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Alten_Gonzalez.Models
{
    public partial class ECOMMERCEContext : DbContext
    {
        public ECOMMERCEContext()
        {
        }

        public ECOMMERCEContext(DbContextOptions<ECOMMERCEContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Carrelli> Carrellis { get; set; }
        public virtual DbSet<Prodotti> Prodottis { get; set; }
        public virtual DbSet<ProdottiCarrello> ProdottiCarrellos { get; set; }
        public virtual DbSet<Utenti> Utentis { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Carrelli>(entity =>
            {
                entity.ToTable("CARRELLI");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.IdUtente).HasColumnName("id_utente");

                entity.HasOne(d => d.IdUtenteNavigation)
                    .WithMany(p => p.Carrellis)
                    .HasForeignKey(d => d.IdUtente)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__CARRELLI__id_ute__3A81B327");
            });

            modelBuilder.Entity<Prodotti>(entity =>
            {
                entity.ToTable("PRODOTTI");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("nome");

                entity.Property(e => e.Prezzo).HasColumnName("prezzo");
            });

            modelBuilder.Entity<ProdottiCarrello>(entity =>
            {
                entity.ToTable("PRODOTTI_CARRELLO");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.IdCarrello).HasColumnName("id_carrello");

                entity.Property(e => e.IdProdotto).HasColumnName("id_prodotto");

                entity.Property(e => e.Quantità).HasColumnName("quantità");

                entity.HasOne(d => d.IdCarrelloNavigation)
                    .WithMany(p => p.ProdottiCarrellos)
                    .HasForeignKey(d => d.IdCarrello)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__PRODOTTI___id_ca__3D5E1FD2");

                entity.HasOne(d => d.IdProdottoNavigation)
                    .WithMany(p => p.ProdottiCarrellos)
                    .HasForeignKey(d => d.IdProdotto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__PRODOTTI___id_pr__3E52440B");
            });

            modelBuilder.Entity<Utenti>(entity =>
            {
                entity.ToTable("UTENTI");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("nome");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}