// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Alten_Gonzalez.Models
{
    public partial class Utenti
    {
        public Utenti()
        {
            Carrellis = new HashSet<Carrelli>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }

        public virtual ICollection<Carrelli> Carrellis { get; set; }
    }
}